[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | build
    | dist
  )/
)
'''
line-length = 119

[tool.isort]
include_trailing_comma = true
line_length = 119
multi_line_output = 3
profile = "black"
use_parentheses = true

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 119
disable = [
    "abstract-method",
    "assignment-from-none",
    "attribute-defined-outside-init",
    "broad-except",
    "c-extension-no-member",
    "consider-using-f-string",
    "duplicate-code",
    "global-statement",
    "invalid-name",
    "line-too-long",
    "missing-class-docstring",
    "missing-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "redefined-builtin",
    "redefined-outer-name",
    "too-few-public-methods",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "unused-argument",
]
