[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | build
    | dist
  )/
)
'''
line-length = 119

[tool.isort]
include_trailing_comma = true
line_length = 119
multi_line_output = 3
profile = "black"
use_parentheses = true

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 119
disable = [
    "consider-using-f-string",
    "missing-docstring",
    "invalid-name",
    "redefined-builtin",
    "redefined-outer-name",
]
